#!/usr/bin/with-contenv sh
HOME=/home/$USER_NAME-cont
export HOME
echo "Starting tigervnc for user $USER_NAME with home = ${HOME} on DISPLAY $DISPLAY ..."
echo "Starting tigervnc with depth $VNC_COL_DEPTH and geometry $VNC_RESOLUTION ..."
s6-setuidgid $USER_NAME vncserver -fg $DISPLAY -depth $VNC_COL_DEPTH -geometry $VNC_RESOLUTION > /tmp/no_vnc_startup.log
