#!/usr/bin/with-contenv sh
echo "Starting window manager for user $USER_NAME on DISPLAY $DISPLAY ..."

# first we wait for the vncserver
until pids=$(pidof Xtigervnc)
do   
    sleep 1
done
HOME=/home/$USER_NAME
export HOME
s6-setuidgid $USER_NAME $HOME/wm_startup.sh > /tmp/wm_startup.log
